const cangKuInfo = {
  "id": "25",
  "icon": null,
  "funcCode": "cangKuInfo",
  "funcName": "仓库信息",
  "state": "A",
  "comments": null,
  "stateTime": "2020-06-27 03:11:58",
  "seq": 25,
  "indexUrl": null,
  "dictList": [
    {
      "id": "18",
      "funcId": "25",
      "dictName": "灵物分类",
      "dictCode": "lingWuFenLei",
      "comments": null,
      "category": null,
      "modifyFlag": null,
      "visiableFlag": null,
      "seq": 1,
      "spId": null,
      "version": 0,
      "dictDataList": [
        {
          "id": "167",
          "dictId": "18",
          "dataName": "阵法",
          "dataCode": "zhenFa",
          "seq": 10,
          "spId": null,
          "version": 0
        },
        {
          "id": "168",
          "dictId": "18",
          "dataName": "人物",
          "dataCode": "renWu",
          "seq": 11,
          "spId": null,
          "version": 0
        },
        {
          "id": "169",
          "dictId": "18",
          "dataName": "妖兽",
          "dataCode": "yaoShou",
          "seq": 1,
          "spId": null,
          "version": 0
        },
        {
          "id": "170",
          "dictId": "18",
          "dataName": "符箓",
          "dataCode": "fuLu",
          "seq": 2,
          "spId": null,
          "version": 0
        },
        {
          "id": "171",
          "dictId": "18",
          "dataName": "功法",
          "dataCode": "gongFa",
          "seq": 3,
          "spId": null,
          "version": 0
        },
        {
          "id": "172",
          "dictId": "18",
          "dataName": "灵材",
          "dataCode": "lingCai",
          "seq": 4,
          "spId": null,
          "version": 0
        },
        {
          "id": "173",
          "dictId": "18",
          "dataName": "傀儡",
          "dataCode": "kuiLei",
          "seq": 5,
          "spId": null,
          "version": 0
        },
        {
          "id": "174",
          "dictId": "18",
          "dataName": "法术",
          "dataCode": "faShu",
          "seq": 6,
          "spId": null,
          "version": 0
        },
        {
          "id": "175",
          "dictId": "18",
          "dataName": "法器",
          "dataCode": "faQi",
          "seq": 7,
          "spId": null,
          "version": 0
        },
        {
          "id": "176",
          "dictId": "18",
          "dataName": "其他灵物",
          "dataCode": "qiTaLingWu",
          "seq": 8,
          "spId": null,
          "version": 0
        },
        {
          "id": "177",
          "dictId": "18",
          "dataName": "灵丹",
          "dataCode": "lingDan",
          "seq": 9,
          "spId": null,
          "version": 0
        }
      ]
    },
    {
      "id": "19",
      "funcId": "25",
      "dictName": "所属分类",
      "dictCode": "suoShuFenLei",
      "comments": null,
      "category": null,
      "modifyFlag": null,
      "visiableFlag": null,
      "seq": 2,
      "spId": null,
      "version": 0,
      "dictDataList": [
        {
          "id": "178",
          "dictId": "19",
          "dataName": "地名",
          "dataCode": "diMing",
          "seq": 1,
          "spId": null,
          "version": 0
        },
        {
          "id": "179",
          "dictId": "19",
          "dataName": "组织",
          "dataCode": "zuZhi",
          "seq": 5,
          "spId": null,
          "version": 0
        },
        {
          "id": "180",
          "dictId": "19",
          "dataName": "机构",
          "dataCode": "jiGou",
          "seq": 2,
          "spId": null,
          "version": 0
        },
        {
          "id": "181",
          "dictId": "19",
          "dataName": "宗门",
          "dataCode": "zongMen",
          "seq": 3,
          "spId": null,
          "version": 0
        },
        {
          "id": "182",
          "dictId": "19",
          "dataName": "家族",
          "dataCode": "jiaZu",
          "seq": 4,
          "spId": null,
          "version": 0
        },
        {
          "id": "dc654cc8c8aa46ac42e681203e9fc247",
          "dictId": "19",
          "dataName": "修行者",
          "dataCode": "xiuXingZhe",
          "seq": 6,
          "spId": null,
          "version": 0
        }
      ]
    },
    {
      "id": "20",
      "funcId": "25",
      "dictName": "灵物状态",
      "dictCode": "lingWuState",
      "comments": null,
      "category": null,
      "modifyFlag": null,
      "visiableFlag": null,
      "seq": 3,
      "spId": null,
      "version": 0,
      "dictDataList": [
        {
          "id": "3f9712616dd142cb9474ecd73d710544",
          "dictId": "20",
          "dataName": "已损坏",
          "dataCode": "已损坏",
          "seq": 7,
          "spId": null,
          "version": 0
        },
        {
          "id": "5100d1b4bb11497587aae51467b00731",
          "dictId": "20",
          "dataName": "已毁灭",
          "dataCode": "已毁灭",
          "seq": 10,
          "spId": null,
          "version": 0
        },
        {
          "id": "6298d14f942249fc93de6ae05e117b95",
          "dictId": "20",
          "dataName": "已粉碎",
          "dataCode": "已粉碎",
          "seq": 11,
          "spId": null,
          "version": 0
        },
        {
          "id": "675251740f8f4f09ba577e306503b89f",
          "dictId": "20",
          "dataName": "已残缺",
          "dataCode": "已残缺",
          "seq": 2,
          "spId": null,
          "version": 0
        },
        {
          "id": "734cc5b2862c4e28a4378790564f1857",
          "dictId": "20",
          "dataName": "已发完",
          "dataCode": "已发完",
          "seq": 8,
          "spId": null,
          "version": 0
        },
        {
          "id": "829120a69b39488da69c965fc667cca4",
          "dictId": "20",
          "dataName": "已死亡",
          "dataCode": "已死亡",
          "seq": 9,
          "spId": null,
          "version": 0
        },
        {
          "id": "9decfa063c814da3a3819677472fffe6",
          "dictId": "20",
          "dataName": "已使用",
          "dataCode": "已使用",
          "seq": 1,
          "spId": null,
          "version": 0
        },
        {
          "id": "ac79b268ec6840448881ab356d32e622",
          "dictId": "20",
          "dataName": "已消耗",
          "dataCode": "已消耗",
          "seq": 4,
          "spId": null,
          "version": 0
        },
        {
          "id": "ae5aa216f6c841699bcc5984c9e16545",
          "dictId": "20",
          "dataName": "已服用",
          "dataCode": "已服用",
          "seq": 6,
          "spId": null,
          "version": 0
        },
        {
          "id": "af81eb0e84ef4c53b42719c99012f7ee",
          "dictId": "20",
          "dataName": "已耗尽",
          "dataCode": "已耗尽",
          "seq": 5,
          "spId": null,
          "version": 0
        },
        {
          "id": "bdfba897dbbd433295b2685ceb86bd08",
          "dictId": "20",
          "dataName": "已掉落",
          "dataCode": "已掉落",
          "seq": 12,
          "spId": null,
          "version": 0
        },
        {
          "id": "ec17468231e348dca2806bc902b1fee6",
          "dictId": "20",
          "dataName": "已腐蚀",
          "dataCode": "已腐蚀",
          "seq": 3,
          "spId": null,
          "version": 0
        }
      ]
    },
    {
      "id": "21",
      "funcId": "25",
      "dictName": "单位",
      "dictCode": "danWei",
      "comments": null,
      "category": null,
      "modifyFlag": null,
      "visiableFlag": null,
      "seq": 4,
      "spId": null,
      "version": 0,
      "dictDataList": [
        {
          "id": "01cb0383223d4e72bfd9efd74e7f7d54",
          "dictId": "21",
          "dataName": "艘",
          "dataCode": "艘",
          "seq": 26,
          "spId": null,
          "version": 0
        },
        {
          "id": "11811ef115a54f01b7fbbdcd4f549f4d",
          "dictId": "21",
          "dataName": "双",
          "dataCode": "双",
          "seq": 30,
          "spId": null,
          "version": 0
        },
        {
          "id": "16a9b046342a42df91791cfea5fdcc2c",
          "dictId": "21",
          "dataName": "块",
          "dataCode": "块",
          "seq": 5,
          "spId": null,
          "version": 0
        },
        {
          "id": "1bb36d903c874f2092a3cd314b00b72d",
          "dictId": "21",
          "dataName": "张",
          "dataCode": "张",
          "seq": 3,
          "spId": null,
          "version": 0
        },
        {
          "id": "1e6faedc711e459083568f14c2893ac3",
          "dictId": "21",
          "dataName": "条",
          "dataCode": "条",
          "seq": 33,
          "spId": null,
          "version": 0
        },
        {
          "id": "217bca4a485048c693bf7b5d821b4e66",
          "dictId": "21",
          "dataName": "束",
          "dataCode": "束",
          "seq": 7,
          "spId": null,
          "version": 0
        },
        {
          "id": "21f08891a82247d0b24f36f85a32d624",
          "dictId": "21",
          "dataName": "道",
          "dataCode": "道",
          "seq": 9,
          "spId": null,
          "version": 0
        },
        {
          "id": "27948850905b41ae878e9a61ff85dd38",
          "dictId": "21",
          "dataName": "打",
          "dataCode": "打",
          "seq": 2,
          "spId": null,
          "version": 0
        },
        {
          "id": "2e391ef0ecf942ae8751144c7bac1542",
          "dictId": "21",
          "dataName": "套",
          "dataCode": "套",
          "seq": 17,
          "spId": null,
          "version": 0
        },
        {
          "id": "2f1c643fa3cf47e18748b16fad327ded",
          "dictId": "21",
          "dataName": "片",
          "dataCode": "片",
          "seq": 12,
          "spId": null,
          "version": 0
        },
        {
          "id": "3deafcc064f843a5830dee516a605a6d",
          "dictId": "21",
          "dataName": "瓶",
          "dataCode": "瓶",
          "seq": 6,
          "spId": null,
          "version": 0
        },
        {
          "id": "47ae1f64e99945e68fc7c566bbf5ce4e",
          "dictId": "21",
          "dataName": "些",
          "dataCode": "些",
          "seq": 31,
          "spId": null,
          "version": 0
        },
        {
          "id": "4a6b47bacee342cdbd459e37da7f4284",
          "dictId": "21",
          "dataName": "尊",
          "dataCode": "尊",
          "seq": 36,
          "spId": null,
          "version": 0
        },
        {
          "id": "4be87385ba3b4f259b8da7ce2249d16b",
          "dictId": "21",
          "dataName": "条",
          "dataCode": "条",
          "seq": 23,
          "spId": null,
          "version": 0
        },
        {
          "id": "4d140a27afb049539bb252f6b4afdc5a",
          "dictId": "21",
          "dataName": "枚",
          "dataCode": "枚",
          "seq": 14,
          "spId": null,
          "version": 0
        },
        {
          "id": "518bbedd5c5d431ab95c01e4ade28d39",
          "dictId": "21",
          "dataName": "种",
          "dataCode": "种",
          "seq": 35,
          "spId": null,
          "version": 0
        },
        {
          "id": "5472a0acfdc04fc5922f492f4e0f9023",
          "dictId": "21",
          "dataName": "根",
          "dataCode": "根",
          "seq": 22,
          "spId": null,
          "version": 0
        },
        {
          "id": "59ac3d945423487582db112433ee4f68",
          "dictId": "21",
          "dataName": "亩",
          "dataCode": "亩",
          "seq": 11,
          "spId": null,
          "version": 0
        },
        {
          "id": "71b8ba6c5d774b1185406e3699d22de9",
          "dictId": "21",
          "dataName": "个",
          "dataCode": "个",
          "seq": 13,
          "spId": null,
          "version": 0
        },
        {
          "id": "975efbb5cfce4cf9ba7f7c6d9065c6c7",
          "dictId": "21",
          "dataName": "件",
          "dataCode": "件",
          "seq": 16,
          "spId": null,
          "version": 0
        },
        {
          "id": "9907dc8b5d994b31a8ee983c6827f3fe",
          "dictId": "21",
          "dataName": "服",
          "dataCode": "服",
          "seq": 21,
          "spId": null,
          "version": 0
        },
        {
          "id": "9b12e96d5bdb4f87a81142ea5099d131",
          "dictId": "21",
          "dataName": "壶",
          "dataCode": "壶",
          "seq": 37,
          "spId": null,
          "version": 0
        },
        {
          "id": "a719cae73e4c4c97aa6303cc864a4a31",
          "dictId": "21",
          "dataName": "面",
          "dataCode": "面",
          "seq": 18,
          "spId": null,
          "version": 0
        },
        {
          "id": "a9f7b72031a245958e2d3bceaf474ce9",
          "dictId": "21",
          "dataName": "柄",
          "dataCode": "柄",
          "seq": 27,
          "spId": null,
          "version": 0
        },
        {
          "id": "aea4886dcd4d4e68a75077db1d1ab419",
          "dictId": "21",
          "dataName": "粒",
          "dataCode": "粒",
          "seq": 20,
          "spId": null,
          "version": 0
        },
        {
          "id": "bda8574521284872aa5ade3d9248c72d",
          "dictId": "21",
          "dataName": "只",
          "dataCode": "只",
          "seq": 1,
          "spId": null,
          "version": 0
        },
        {
          "id": "cfebe99d3eb346bdaf9979c6026c98b6",
          "dictId": "21",
          "dataName": "株",
          "dataCode": "株",
          "seq": 10,
          "spId": null,
          "version": 0
        },
        {
          "id": "d0d1d08f24e5408eba2e922b8122d7f2",
          "dictId": "21",
          "dataName": "杆",
          "dataCode": "杆",
          "seq": 15,
          "spId": null,
          "version": 0
        },
        {
          "id": "d3ad06e5f925401bbe5062ff216e28d5",
          "dictId": "21",
          "dataName": "群",
          "dataCode": "群",
          "seq": 29,
          "spId": null,
          "version": 0
        },
        {
          "id": "d400b0642ecc4ce195d769875f1870d6",
          "dictId": "21",
          "dataName": "位",
          "dataCode": "位",
          "seq": 8,
          "spId": null,
          "version": 0
        },
        {
          "id": "db3972cf74514799a695391bf9ee45f5",
          "dictId": "21",
          "dataName": "部",
          "dataCode": "部",
          "seq": 19,
          "spId": null,
          "version": 0
        },
        {
          "id": "e13aa6aeb35241668d715f6686a5b419",
          "dictId": "21",
          "dataName": "颗",
          "dataCode": "颗",
          "seq": 25,
          "spId": null,
          "version": 0
        },
        {
          "id": "e319ecc319ad413582e765db3593ca98",
          "dictId": "21",
          "dataName": "本",
          "dataCode": "本",
          "seq": 4,
          "spId": null,
          "version": 0
        },
        {
          "id": "e89cf0eb0e8f4b4c87450e6a9acba2c9",
          "dictId": "21",
          "dataName": "口",
          "dataCode": "口",
          "seq": 34,
          "spId": null,
          "version": 0
        },
        {
          "id": "e8fd548ad316375e7aed8ddcff848e06",
          "dictId": "21",
          "dataName": "朵",
          "dataCode": "朵",
          "seq": 38,
          "spId": null,
          "version": 0
        },
        {
          "id": "eae733363fc640f9835620fcd21877ee",
          "dictId": "21",
          "dataName": "头",
          "dataCode": "头",
          "seq": 32,
          "spId": null,
          "version": 0
        },
        {
          "id": "ecdbf7940d9e42edba47494029019c74",
          "dictId": "21",
          "dataName": "把",
          "dataCode": "把",
          "seq": 24,
          "spId": null,
          "version": 0
        },
        {
          "id": "ff698e396bee47c4b4559ae4b846cdcb",
          "dictId": "21",
          "dataName": "份",
          "dataCode": "份",
          "seq": 28,
          "spId": null,
          "version": 0
        }
      ]
    }
  ],
  "configList": [],
  "funcComponentList": [],
  "metaModelList": [
    {
      "id": "25",
      "parentModelId": null,
      "relationship": null,
      "modelName": "仓库信息",
      "modelCode": "cangKuInfo",
      "funcModelCode": "cangKuInfo",
      "searchFlag": "Y",
      "multChooseFlag": "Y",
      "title": null,
      "masterFlag": "Y",
      "treeTableFlag": "N",
      "childColumnCode": null,
      "parentColumnCode": null,
      "position": "1",
      "state": null,
      "stateTime": null,
      "columnList": [
        {
          "id": "220",
          "modelId": "25",
          "columnName": "id",
          "columnCode": "id",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 1,
          "requiredFlag": "Y",
          "searchFlag": "N",
          "profileDisplayFlag": "N",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "Y",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "222",
          "modelId": "25",
          "columnName": "灵物分类",
          "columnCode": "lingWuFenLei",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "S",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": "service|xiuXing/common/xiu-xing/fenLei?type=fenLei&fenLei=lingWuFenLei",
          "seq": 3,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "N",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "da2470c16af80016dd0e5d7b8976a644",
          "modelId": "25",
          "columnName": "灵物分类",
          "columnCode": "lingWuFenLeiName",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 3,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "221",
          "modelId": "25",
          "columnName": "灵物名称",
          "columnCode": "lingWuName",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 4,
          "requiredFlag": "Y",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "242",
          "modelId": "25",
          "columnName": "灵物全名",
          "columnCode": "lingWuFullName",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 5,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "223",
          "modelId": "25",
          "columnName": "灵物属性",
          "columnCode": "lingWuShuXing",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 7,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "N",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "224",
          "modelId": "25",
          "columnName": "灵物状态",
          "columnCode": "lingWuState",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "S",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": "service|xiuXing/common/xiu-xing/fenLei?type=state&fenLei=lingWuState",
          "seq": 9,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "N",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "f28adc53ec2e779c05d428417790cbd7",
          "modelId": "25",
          "columnName": "灵物状态",
          "columnCode": "lingWuStateName",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 9,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "225",
          "modelId": "25",
          "columnName": "灵物数量",
          "columnCode": "lingWuShuLiang",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 11,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "N",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "226",
          "modelId": "25",
          "columnName": "单位",
          "columnCode": "danWei",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "S",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": "dict|danWei",
          "seq": 13,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "N",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "235",
          "modelId": "25",
          "columnName": "灵物境界",
          "columnCode": "jingJieId",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "S",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": "service|/xiuXing/common/xiu-xing/jingJie",
          "seq": 15,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "N",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "229",
          "modelId": "25",
          "columnName": "灵物境界",
          "columnCode": "jingJieName",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 17,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "N",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "236",
          "modelId": "25",
          "columnName": "灵物品级",
          "columnCode": "pinJiId",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "S",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": "service|/xiuXing/common/xiu-xing/pinJi",
          "seq": 19,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "N",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "230",
          "modelId": "25",
          "columnName": "灵物品级",
          "columnCode": "pinJiName",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 21,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "N",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "231",
          "modelId": "25",
          "columnName": "灵物描述",
          "columnCode": "lingWuMiaoShu",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "T",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 23,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": "renderMiaoShu",
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": "300px",
          "titleFlag": "N"
        },
        {
          "id": "227",
          "modelId": "25",
          "columnName": "所属分类",
          "columnCode": "suoShuFenLei",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "S",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": "service|xiuXing/common/xiu-xing/fenLei?type=fenLei&fenLei=suoShuFenLei",
          "seq": 25,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "N",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "92b453efecb1257b0734cdde2487ee9f",
          "modelId": "25",
          "columnName": "所属分类",
          "columnCode": "suoShuFenLeiName",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 25,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "228",
          "modelId": "25",
          "columnName": "所属名称",
          "columnCode": "suoShuName",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 26,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "243",
          "modelId": "25",
          "columnName": "所属全名",
          "columnCode": "suoShuFullName",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 27,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "237",
          "modelId": "25",
          "columnName": "所属境界",
          "columnCode": "suoShuJingJieId",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "S",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": "service|/xiuXing/common/xiu-xing/jingJie",
          "seq": 29,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "N",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "238",
          "modelId": "25",
          "columnName": "所属境界",
          "columnCode": "suoShuJingJieName",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 31,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "239",
          "modelId": "25",
          "columnName": "所属品级",
          "columnCode": "suoShuPinJiId",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "S",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": "service|/xiuXing/common/xiu-xing/pinJi",
          "seq": 33,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "N",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "240",
          "modelId": "25",
          "columnName": "所属品级",
          "columnCode": "suoShuPinJiName",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 35,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "241",
          "modelId": "25",
          "columnName": "所属描述",
          "columnCode": "suoShuMiaoShu",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "T",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 37,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": "renderMiaoShu",
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": "300px",
          "titleFlag": "N"
        },
        {
          "id": "232",
          "modelId": "25",
          "columnName": "小说",
          "columnCode": "xiaoShuoId",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "S",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": "service|/xiuXing/common/xiu-xing/xiaoShuo",
          "seq": 39,
          "requiredFlag": "Y",
          "searchFlag": "Y",
          "profileDisplayFlag": "N",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "233",
          "modelId": "25",
          "columnName": "小说",
          "columnCode": "xiaoShuoName",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 41,
          "requiredFlag": "Y",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "234",
          "modelId": "25",
          "columnName": "更新时间",
          "columnCode": "updateTime",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 43,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": "160px",
          "titleFlag": "N"
        }
      ],
      "actionList": [
        {
          "id": "113",
          "modelId": "25",
          "type": "N",
          "code": "query",
          "name": null,
          "servId": "25",
          "servAction": "query",
          "defaultFlag": "Y",
          "disableRule": null,
          "propFlag": "N",
          "propMsg": null,
          "delErrorMsg": null,
          "servCode": null,
          "category": null,
          "seq": 1,
          "displayType": null,
          "icon": null
        },
        {
          "id": "114",
          "modelId": "25",
          "type": "N",
          "code": "get",
          "name": null,
          "servId": "25",
          "servAction": "get",
          "defaultFlag": "Y",
          "disableRule": null,
          "propFlag": "N",
          "propMsg": null,
          "delErrorMsg": null,
          "servCode": null,
          "category": null,
          "seq": 2,
          "displayType": null,
          "icon": null
        }
      ]
    }
  ]
};

export function cangKuInfoMetaModel() {
  return cangKuInfo;
}
