const cangKu = {
  "id": "21",
  "icon": null,
  "funcCode": "cangKu",
  "funcName": "仓库",
  "state": "A",
  "comments": null,
  "stateTime": "2020-06-16 14:20:13",
  "seq": 21,
  "indexUrl": null,
  "dictList": [
    {
      "id": "10",
      "funcId": "21",
      "dictName": "灵物分类",
      "dictCode": "lingWuFenLei",
      "comments": null,
      "category": null,
      "modifyFlag": null,
      "visiableFlag": null,
      "seq": 1,
      "spId": null,
      "version": 0,
      "dictDataList": [
        {
          "id": "82",
          "dictId": "10",
          "dataName": "妖兽",
          "dataCode": "妖兽",
          "seq": 1,
          "spId": null,
          "version": 0
        },
        {
          "id": "83",
          "dictId": "10",
          "dataName": "符箓",
          "dataCode": "符箓",
          "seq": 2,
          "spId": null,
          "version": 0
        },
        {
          "id": "84",
          "dictId": "10",
          "dataName": "功法",
          "dataCode": "功法",
          "seq": 3,
          "spId": null,
          "version": 0
        },
        {
          "id": "85",
          "dictId": "10",
          "dataName": "灵材",
          "dataCode": "灵材",
          "seq": 4,
          "spId": null,
          "version": 0
        },
        {
          "id": "86",
          "dictId": "10",
          "dataName": "傀儡",
          "dataCode": "傀儡",
          "seq": 5,
          "spId": null,
          "version": 0
        },
        {
          "id": "87",
          "dictId": "10",
          "dataName": "法术",
          "dataCode": "法术",
          "seq": 6,
          "spId": null,
          "version": 0
        },
        {
          "id": "88",
          "dictId": "10",
          "dataName": "法器",
          "dataCode": "法器",
          "seq": 7,
          "spId": null,
          "version": 0
        },
        {
          "id": "89",
          "dictId": "10",
          "dataName": "其他灵物",
          "dataCode": "其他灵物",
          "seq": 8,
          "spId": null,
          "version": 0
        },
        {
          "id": "90",
          "dictId": "10",
          "dataName": "灵丹",
          "dataCode": "灵丹",
          "seq": 9,
          "spId": null,
          "version": 0
        }
      ]
    },
    {
      "id": "11",
      "funcId": "21",
      "dictName": "所属分类",
      "dictCode": "suoShuFenLei",
      "comments": null,
      "category": null,
      "modifyFlag": null,
      "visiableFlag": null,
      "seq": 2,
      "spId": null,
      "version": 0,
      "dictDataList": [
        {
          "id": "91",
          "dictId": "11",
          "dataName": "地名",
          "dataCode": "地名",
          "seq": 1,
          "spId": null,
          "version": 0
        },
        {
          "id": "92",
          "dictId": "11",
          "dataName": "机构",
          "dataCode": "机构",
          "seq": 2,
          "spId": null,
          "version": 0
        },
        {
          "id": "93",
          "dictId": "11",
          "dataName": "宗门",
          "dataCode": "宗门",
          "seq": 3,
          "spId": null,
          "version": 0
        },
        {
          "id": "94",
          "dictId": "11",
          "dataName": "家族",
          "dataCode": "家族",
          "seq": 4,
          "spId": null,
          "version": 0
        }
      ]
    },
    {
      "id": "12",
      "funcId": "21",
      "dictName": "灵物状态",
      "dictCode": "lingWuState",
      "comments": null,
      "category": null,
      "modifyFlag": null,
      "visiableFlag": null,
      "seq": 3,
      "spId": null,
      "version": 0,
      "dictDataList": [
        {
          "id": "100",
          "dictId": "12",
          "dataName": "已服用",
          "dataCode": "已服用",
          "seq": 6,
          "spId": null,
          "version": 0
        },
        {
          "id": "101",
          "dictId": "12",
          "dataName": "已损坏",
          "dataCode": "已损坏",
          "seq": 7,
          "spId": null,
          "version": 0
        },
        {
          "id": "102",
          "dictId": "12",
          "dataName": "已发完",
          "dataCode": "已发完",
          "seq": 8,
          "spId": null,
          "version": 0
        },
        {
          "id": "103",
          "dictId": "12",
          "dataName": "已死亡",
          "dataCode": "已死亡",
          "seq": 9,
          "spId": null,
          "version": 0
        },
        {
          "id": "104",
          "dictId": "12",
          "dataName": "已毁灭",
          "dataCode": "已毁灭",
          "seq": 10,
          "spId": null,
          "version": 0
        },
        {
          "id": "105",
          "dictId": "12",
          "dataName": "已粉碎",
          "dataCode": "已粉碎",
          "seq": 11,
          "spId": null,
          "version": 0
        },
        {
          "id": "106",
          "dictId": "12",
          "dataName": "已掉落",
          "dataCode": "已掉落",
          "seq": 12,
          "spId": null,
          "version": 0
        },
        {
          "id": "95",
          "dictId": "12",
          "dataName": "已使用",
          "dataCode": "已使用",
          "seq": 1,
          "spId": null,
          "version": 0
        },
        {
          "id": "96",
          "dictId": "12",
          "dataName": "已残缺",
          "dataCode": "已残缺",
          "seq": 2,
          "spId": null,
          "version": 0
        },
        {
          "id": "97",
          "dictId": "12",
          "dataName": "已腐蚀",
          "dataCode": "已腐蚀",
          "seq": 3,
          "spId": null,
          "version": 0
        },
        {
          "id": "98",
          "dictId": "12",
          "dataName": "已消耗",
          "dataCode": "已消耗",
          "seq": 4,
          "spId": null,
          "version": 0
        },
        {
          "id": "99",
          "dictId": "12",
          "dataName": "已耗尽",
          "dataCode": "已耗尽",
          "seq": 5,
          "spId": null,
          "version": 0
        }
      ]
    }
  ],
  "configList": [],
  "funcComponentList": [
    {
      "id": "52",
      "funcId": "21",
      "name": "新增",
      "code": "add",
      "icon": null,
      "displayType": "primary",
      "comments": null
    },
    {
      "id": "53",
      "funcId": "21",
      "name": "编辑",
      "code": "update",
      "icon": null,
      "displayType": null,
      "comments": null
    },
    {
      "id": "54",
      "funcId": "21",
      "name": "删除",
      "code": "delete",
      "icon": null,
      "displayType": null,
      "comments": null
    }
  ],
  "metaModelList": [
    {
      "id": "21",
      "parentModelId": null,
      "relationship": null,
      "modelName": "仓库",
      "modelCode": "cangKu",
      "funcModelCode": "cangKu",
      "searchFlag": "Y",
      "multChooseFlag": "Y",
      "title": null,
      "masterFlag": "Y",
      "treeTableFlag": "N",
      "childColumnCode": null,
      "parentColumnCode": null,
      "position": "1",
      "state": null,
      "stateTime": null,
      "columnList": [
        {
          "id": "158",
          "modelId": "21",
          "columnName": "id",
          "columnCode": "id",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 1,
          "requiredFlag": "Y",
          "searchFlag": "N",
          "profileDisplayFlag": "N",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "Y",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "159",
          "modelId": "21",
          "columnName": "灵物名称",
          "columnCode": "lingWuName",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 3,
          "requiredFlag": "Y",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "160",
          "modelId": "21",
          "columnName": "灵物分类",
          "columnCode": "lingWuFenLei",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "S",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": "dict|lingWuFenLei",
          "seq": 5,
          "requiredFlag": "Y",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "161",
          "modelId": "21",
          "columnName": "灵物属性",
          "columnCode": "lingWuShuXing",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 7,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "162",
          "modelId": "21",
          "columnName": "灵物状态",
          "columnCode": "lingWuState",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "S",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": "dict|lingWuState",
          "seq": 9,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "163",
          "modelId": "21",
          "columnName": "灵物数量",
          "columnCode": "lingWuShuLiang",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 11,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "164",
          "modelId": "21",
          "columnName": "单位",
          "columnCode": "danWei",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 13,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "165",
          "modelId": "21",
          "columnName": "所属分类",
          "columnCode": "suoShuFenLei",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "S",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": "dict|suoShuFenLei",
          "seq": 15,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "166",
          "modelId": "21",
          "columnName": "所属者",
          "columnCode": "suoShuZhe",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 17,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "167",
          "modelId": "21",
          "columnName": "境界",
          "columnCode": "jingJieName",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 19,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "168",
          "modelId": "21",
          "columnName": "品级",
          "columnCode": "pinJiName",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 21,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "169",
          "modelId": "21",
          "columnName": "描述",
          "columnCode": "lingWuMiaoShu",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 23,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": "renderMiaoShu",
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": "300px",
          "titleFlag": "N"
        },
        {
          "id": "170",
          "modelId": "21",
          "columnName": "小说",
          "columnCode": "xiaoShuoId",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "S",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": "service|/xiuXing/common/xiu-xing/xiaoShuo",
          "seq": 25,
          "requiredFlag": "Y",
          "searchFlag": "Y",
          "profileDisplayFlag": "N",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "171",
          "modelId": "21",
          "columnName": "小说",
          "columnCode": "xiaoShuoName",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 27,
          "requiredFlag": "Y",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "172",
          "modelId": "21",
          "columnName": "更新时间",
          "columnCode": "updateTime",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 29,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": "160px",
          "titleFlag": "N"
        }
      ],
      "actionList": [
        {
          "id": "93",
          "modelId": "21",
          "type": "N",
          "code": "query",
          "name": null,
          "servId": "21",
          "servAction": "query",
          "defaultFlag": "Y",
          "disableRule": null,
          "propFlag": "N",
          "propMsg": null,
          "delErrorMsg": null,
          "servCode": null,
          "category": null,
          "seq": null,
          "displayType": null,
          "icon": null
        },
        {
          "id": "94",
          "modelId": "21",
          "type": "N",
          "code": "get",
          "name": null,
          "servId": "21",
          "servAction": "get",
          "defaultFlag": "Y",
          "disableRule": null,
          "propFlag": "N",
          "propMsg": null,
          "delErrorMsg": null,
          "servCode": null,
          "category": null,
          "seq": null,
          "displayType": null,
          "icon": null
        },
        {
          "id": "95",
          "modelId": "21",
          "type": "T",
          "code": "add",
          "name": "新增",
          "servId": "21",
          "servAction": "add",
          "defaultFlag": "Y",
          "disableRule": null,
          "propFlag": "N",
          "propMsg": null,
          "delErrorMsg": null,
          "servCode": null,
          "category": null,
          "seq": null,
          "displayType": "primary",
          "icon": null
        },
        {
          "id": "96",
          "modelId": "21",
          "type": "L",
          "code": "update",
          "name": "编辑",
          "servId": "21",
          "servAction": "update",
          "defaultFlag": "Y",
          "disableRule": null,
          "propFlag": "N",
          "propMsg": null,
          "delErrorMsg": null,
          "servCode": null,
          "category": null,
          "seq": null,
          "displayType": null,
          "icon": null
        },
        {
          "id": "97",
          "modelId": "21",
          "type": "L",
          "code": "delete",
          "name": "删除",
          "servId": "21",
          "servAction": "delete",
          "defaultFlag": "Y",
          "disableRule": null,
          "propFlag": "Y",
          "propMsg": null,
          "delErrorMsg": null,
          "servCode": null,
          "category": null,
          "seq": null,
          "displayType": null,
          "icon": null
        }
      ]
    }
  ]
};

export function cangKuMetaModel() {
  return cangKu;
}
