const congShuHis = {
  "id": "36",
  "funcCode": "congShuHis",
  "funcName": "从属操作记录",
  "state": "A",
  "stateTime": "2020-10-08 11:10:57",
  "seq": 36,
  "dictList": [
    {
      "id": "26",
      "funcId": "36",
      "dictName": "从属类型",
      "dictCode": "congShuType",
      "seq": 1,
      "version": 0,
      "dictDataList": [
        {
          "id": "442052e1650a41f59b5de2ef13b80e91",
          "dictId": "26",
          "dataName": "从属",
          "dataCode": "从属",
          "seq": 3,
          "version": 0
        },
        {
          "id": "7631a6441f384d77b3f18cb75286be34",
          "dictId": "26",
          "dataName": "从",
          "dataCode": "从",
          "seq": 1,
          "version": 0
        },
        {
          "id": "b0c7f3e15fe0440ca3a7e532749c0ef2",
          "dictId": "26",
          "dataName": "属",
          "dataCode": "属",
          "seq": 2,
          "version": 0
        }
      ]
    }
  ],
  "configList": [],
  "funcComponentList": [
    {
      "id": "36229726624b4f3aa6953ff0014e2839",
      "funcId": "36",
      "name": "删除",
      "code": "delete"
    },
    {
      "id": "bb25db87f15b4f328e38dc3a35ec9c9c",
      "funcId": "36",
      "name": "编辑",
      "code": "update"
    },
    {
      "id": "c97db3c88b294a8983f75a76dee276a7",
      "funcId": "36",
      "name": "新增",
      "code": "add",
      "displayType": "primary"
    }
  ],
  "metaModelList": [
    {
      "id": "36",
      "modelName": "从属操作记录",
      "modelCode": "congShuHis",
      "funcModelCode": "congShuHis",
      "searchFlag": "Y",
      "multChooseFlag": "Y",
      "masterFlag": "Y",
      "treeTableFlag": "N",
      "position": "1",
      "columnList": [
        {
          "id": "5e3dc77029e44c069c3855a5e5347d0d",
          "modelId": "36",
          "columnName": "id",
          "columnCode": "id",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 1,
          "requiredFlag": "Y",
          "searchFlag": "N",
          "profileDisplayFlag": "N",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "Y",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "dc9fb8340b2746cabf0439dbbb89bc05",
          "modelId": "36",
          "columnName": "从属编码",
          "columnCode": "congShuCode",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 2,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "b88be3b0695349b2a0f17572f9e92797",
          "modelId": "36",
          "columnName": "从属名称",
          "columnCode": "congShuName",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 3,
          "requiredFlag": "Y",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "f601468cff764e4499f8327ef8e68e45",
          "modelId": "36",
          "columnName": "从属类型",
          "columnCode": "congShuType",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "S",
          "valueList": "dict|congShuType",
          "seq": 4,
          "requiredFlag": "Y",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "53ba5696411e40f3a58ce1561bca625c",
          "modelId": "36",
          "columnName": "从属分类",
          "columnCode": "congShuFenLei",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "S",
          "valueList": "service|xiuXing/common/xiu-xing/fenLei?type=fenLei&fenLei=congShuFenLei",
          "seq": 5,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "N",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "d7825d3a6a8e41f7b80ab0f951dbcafb",
          "modelId": "36",
          "columnName": "从属分类",
          "columnCode": "congShuFenLeiName",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 5,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "e1b40b3da7d24163bca925e86ae82e7c",
          "modelId": "36",
          "columnName": "从属描述",
          "columnCode": "congShuMiaoShu",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "T",
          "seq": 9,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": "renderMiaoShu",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A",
          "extStr01": "Y"
        },
        {
          "id": "8b210334064a482eb5c8676d5ee89d89",
          "modelId": "36",
          "columnName": "从属地址",
          "columnCode": "addrId",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "CF",
          "valueList": "service|/xiuXing/common/xiu-xing/address",
          "seq": 11,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "N",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "3954e8f7fb014e8497563e2fec360def",
          "modelId": "36",
          "columnName": "从属地址",
          "columnCode": "addrFullName",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 13,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": "renderMiaoShu",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A",
          "extStr01": "Y"
        },
        {
          "id": "03fa026618f7488fb08768825411c1ff",
          "modelId": "36",
          "columnName": "从属小说",
          "columnCode": "xiaoShuoId",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "S",
          "valueList": "service|/xiuXing/common/xiu-xing/xiaoShuo",
          "seq": 15,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "N",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "fd9db40980eb4fc6a73bcc36661170d5",
          "modelId": "36",
          "columnName": "从属小说",
          "columnCode": "xiaoShuoName",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 17,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        }
      ],
      "actionList": [
        {
          "id": "a6e771ac87224f11bc6f86769f9d9747",
          "modelId": "36",
          "type": "N",
          "code": "query",
          "servId": "36",
          "servAction": "query",
          "defaultFlag": "Y",
          "propFlag": "N",
          "seq": 1
        },
        {
          "id": "730adfe911e047e78c566727c5cb03c3",
          "modelId": "36",
          "type": "N",
          "code": "get",
          "servId": "36",
          "servAction": "get",
          "defaultFlag": "Y",
          "propFlag": "N",
          "seq": 2
        },
        {
          "id": "dc2b042d62d34a39a2dd99f881727e16",
          "modelId": "36",
          "type": "L",
          "code": "update",
          "name": "编辑",
          "servId": "36",
          "servAction": "update",
          "defaultFlag": "Y",
          "propFlag": "Y",
          "propMsg": "编辑属性值：\r\n1、从无值到有值；\r\n2、从有值到有值。",
          "seq": 5
        },
        {
          "id": "ee284723ede34f678c8076c878baf34d",
          "modelId": "36",
          "type": "L",
          "code": "delete",
          "name": "删除",
          "servId": "36",
          "servAction": "delete",
          "defaultFlag": "Y",
          "disableRule": "(data,column) => data.cangKuShuHisCount>0",
          "propFlag": "Y",
          "seq": 6
        }
      ]
    }
  ]
};

export function congShuHisMetaModel() {
  return congShuHis;
}
