const congShu = {
  "id": "35",
  "funcCode": "congShu",
  "funcName": "从属",
  "state": "A",
  "stateTime": "2020-10-08 07:57:51",
  "seq": 35,
  "dictList": [
    {
      "id": "25",
      "funcId": "35",
      "dictName": "从属类型",
      "dictCode": "congShuType",
      "seq": 1,
      "version": 0,
      "dictDataList": [
        {
          "id": "2fd4cd97983741b0bd8c8ff902f476c5",
          "dictId": "25",
          "dataName": "属",
          "dataCode": "属",
          "seq": 2,
          "version": 0
        },
        {
          "id": "3155ca1bd6604c10bb9f74f572f09a0b",
          "dictId": "25",
          "dataName": "从属",
          "dataCode": "从属",
          "seq": 3,
          "version": 0
        },
        {
          "id": "d1821dc1d4a24be6b074695ec067a0e0",
          "dictId": "25",
          "dataName": "从",
          "dataCode": "从",
          "seq": 1,
          "version": 0
        }
      ]
    }
  ],
  "configList": [],
  "funcComponentList": [
    {
      "id": "1722919ac0dc4e5c8a0ada937834e9d0",
      "funcId": "35",
      "name": "编辑",
      "code": "update"
    },
    {
      "id": "5bc880a9fd5f474eb8afdc4e6431c6f6",
      "funcId": "35",
      "name": "合并",
      "code": "heBing"
    },
    {
      "id": "8d859f77783f4ff286e718322ffbc051",
      "funcId": "35",
      "name": "删除",
      "code": "delete"
    },
    {
      "id": "acbdd0c359bd4d7b9c8bee59a9490076",
      "funcId": "35",
      "name": "操作记录",
      "code": "opt"
    },
    {
      "id": "b124eed4ac0d4a0fb23378276166bac7",
      "funcId": "35",
      "name": "新增",
      "code": "add",
      "displayType": "primary"
    },
    {
      "id": "edd5099bdd2f41439c17a781e69cb324",
      "funcId": "35",
      "name": "仓库",
      "code": "ck"
    }
  ],
  "metaModelList": [
    {
      "id": "35",
      "modelName": "从属",
      "modelCode": "congShu",
      "funcModelCode": "congShu",
      "searchFlag": "Y",
      "multChooseFlag": "Y",
      "masterFlag": "Y",
      "treeTableFlag": "N",
      "position": "1",
      "columnList": [
        {
          "id": "502efc209f4740f1a1260f0095eccce8",
          "modelId": "35",
          "columnName": "id",
          "columnCode": "id",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 1,
          "requiredFlag": "Y",
          "searchFlag": "N",
          "profileDisplayFlag": "N",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "Y",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "6443779ea3534c2fa1550daa4e5d2f17",
          "modelId": "35",
          "columnName": "从属编码",
          "columnCode": "congShuCode",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 2,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "54f3196839e143228f4fe310107478f4",
          "modelId": "35",
          "columnName": "从属名称",
          "columnCode": "congShuName",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 3,
          "requiredFlag": "Y",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "232a7b4111904a9681868e0da29fe71a",
          "modelId": "35",
          "columnName": "从属类型",
          "columnCode": "congShuType",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "S",
          "valueList": "dict|congShuType",
          "seq": 4,
          "requiredFlag": "Y",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "736ce6dccef743b98caf9290f4144faa",
          "modelId": "35",
          "columnName": "从属分类",
          "columnCode": "congShuFenLeiName",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 5,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "f7fb0a69918747edb8a20b5c56eae670",
          "modelId": "35",
          "columnName": "从属分类",
          "columnCode": "congShuFenLei",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "S",
          "valueList": "service|xiuXing/common/xiu-xing/fenLei?type=fenLei&fenLei=congShuFenLei",
          "seq": 5,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "N",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "81978e369b814bac9a3785d006b3da35",
          "modelId": "35",
          "columnName": "从属描述",
          "columnCode": "congShuMiaoShu",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "T",
          "seq": 7,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": "renderMiaoShu",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A",
          "extStr01": "Y"
        },
        {
          "id": "401fc68b72bc4f0aa73939bba07d61ff",
          "modelId": "35",
          "columnName": "从属地址",
          "columnCode": "addrId",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "CF",
          "valueList": "service|/xiuXing/common/xiu-xing/address",
          "seq": 8,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "N",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "11ae78b1e6bd4dc9a0512461888a3581",
          "modelId": "35",
          "columnName": "从属地址",
          "columnCode": "addrFullName",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 9,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": "renderMiaoShu",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A",
          "extStr01": "Y"
        },
        {
          "id": "fc29f110c24e49a0b149eb3f94a7ab4a",
          "modelId": "35",
          "columnName": "从属小说",
          "columnCode": "xiaoShuoId",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "S",
          "valueList": "service|/xiuXing/common/xiu-xing/xiaoShuo",
          "seq": 10,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "N",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "00896725b7da46e08f1d4ae25d8a4547",
          "modelId": "35",
          "columnName": "从属小说",
          "columnCode": "xiaoShuoName",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 11,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        }
      ],
      "actionList": [
        {
          "id": "fc4cddffe4d84436a42ab81aa84d45e2",
          "modelId": "35",
          "type": "N",
          "code": "query",
          "servId": "35",
          "servAction": "query",
          "defaultFlag": "Y",
          "propFlag": "N",
          "seq": 1
        },
        {
          "id": "a70c6df29a9a41b7970e7e615d108d71",
          "modelId": "35",
          "type": "N",
          "code": "get",
          "servId": "35",
          "servAction": "get",
          "defaultFlag": "Y",
          "propFlag": "N",
          "seq": 2
        },
        {
          "id": "76c237b806a54be08c284d47eff1a0dd",
          "modelId": "35",
          "type": "T",
          "code": "add",
          "name": "新增",
          "servId": "35",
          "servAction": "add",
          "defaultFlag": "Y",
          "propFlag": "N",
          "seq": 3,
          "displayType": "primary"
        },
        {
          "id": "dd9eb0c387ad4438906734539370085d",
          "modelId": "35",
          "type": "L",
          "code": "ck",
          "name": "仓库",
          "servId": "35",
          "servAction": "ck",
          "defaultFlag": "N",
          "disableRule": "(data, column) => data.congShuType === '从'",
          "propFlag": "N",
          "seq": 3
        },
        {
          "id": "850de1b8e439433fb0c2489436f96794",
          "modelId": "35",
          "type": "L",
          "code": "opt",
          "name": "操作记录",
          "servId": "35",
          "servAction": "opt",
          "defaultFlag": "N",
          "propFlag": "N",
          "seq": 4
        },
        {
          "id": "f218b9e81b2f48549fe28281922c6106",
          "modelId": "35",
          "type": "L",
          "code": "update",
          "name": "编辑",
          "servId": "35",
          "servAction": "update",
          "defaultFlag": "Y",
          "propFlag": "N",
          "seq": 5
        },
        {
          "id": "be772b7d1567480fad56874a19ecad3b",
          "modelId": "35",
          "type": "L",
          "code": "delete",
          "name": "删除",
          "servId": "35",
          "servAction": "delete",
          "defaultFlag": "Y",
          "disableRule": "(data, column) => data.congShuHisCount > 0",
          "propFlag": "Y",
          "seq": 7
        },
        {
          "id": "271a18676b4d45bc966824248253e60f",
          "modelId": "35",
          "type": "T",
          "code": "heBing",
          "name": "合并",
          "servId": "35",
          "servAction": "heBing",
          "defaultFlag": "N",
          "propFlag": "N",
          "seq": 8
        }
      ]
    }
  ]
};

export function congShuMetaModel() {
  return congShu;
}
