const diMing = {
  "id": "20",
  "icon": null,
  "funcCode": "diMing",
  "funcName": "地名",
  "state": "A",
  "comments": null,
  "stateTime": "2020-06-16 14:20:13",
  "seq": 20,
  "indexUrl": null,
  "dictList": [
    {
      "id": "9",
      "funcId": "20",
      "dictName": "地名分类",
      "dictCode": "diMingFenLei",
      "comments": null,
      "category": null,
      "modifyFlag": null,
      "visiableFlag": null,
      "seq": 1,
      "spId": null,
      "version": 0,
      "dictDataList": [
        {
          "id": "50",
          "dictId": "9",
          "dataName": "山",
          "dataCode": "山",
          "seq": 1,
          "spId": null,
          "version": 0
        },
        {
          "id": "51",
          "dictId": "9",
          "dataName": "坊",
          "dataCode": "坊",
          "seq": 2,
          "spId": null,
          "version": 0
        },
        {
          "id": "52",
          "dictId": "9",
          "dataName": "潭",
          "dataCode": "潭",
          "seq": 3,
          "spId": null,
          "version": 0
        },
        {
          "id": "53",
          "dictId": "9",
          "dataName": "岛",
          "dataCode": "岛",
          "seq": 4,
          "spId": null,
          "version": 0
        },
        {
          "id": "54",
          "dictId": "9",
          "dataName": "郡",
          "dataCode": "郡",
          "seq": 5,
          "spId": null,
          "version": 0
        },
        {
          "id": "55",
          "dictId": "9",
          "dataName": "洞",
          "dataCode": "洞",
          "seq": 6,
          "spId": null,
          "version": 0
        },
        {
          "id": "56",
          "dictId": "9",
          "dataName": "岭",
          "dataCode": "岭",
          "seq": 7,
          "spId": null,
          "version": 0
        },
        {
          "id": "57",
          "dictId": "9",
          "dataName": "峰",
          "dataCode": "峰",
          "seq": 8,
          "spId": null,
          "version": 0
        },
        {
          "id": "58",
          "dictId": "9",
          "dataName": "城",
          "dataCode": "城",
          "seq": 9,
          "spId": null,
          "version": 0
        },
        {
          "id": "59",
          "dictId": "9",
          "dataName": "渊",
          "dataCode": "渊",
          "seq": 10,
          "spId": null,
          "version": 0
        },
        {
          "id": "60",
          "dictId": "9",
          "dataName": "江",
          "dataCode": "江",
          "seq": 11,
          "spId": null,
          "version": 0
        },
        {
          "id": "61",
          "dictId": "9",
          "dataName": "河",
          "dataCode": "河",
          "seq": 12,
          "spId": null,
          "version": 0
        },
        {
          "id": "62",
          "dictId": "9",
          "dataName": "湖",
          "dataCode": "湖",
          "seq": 13,
          "spId": null,
          "version": 0
        },
        {
          "id": "63",
          "dictId": "9",
          "dataName": "海",
          "dataCode": "海",
          "seq": 14,
          "spId": null,
          "version": 0
        },
        {
          "id": "64",
          "dictId": "9",
          "dataName": "道",
          "dataCode": "道",
          "seq": 15,
          "spId": null,
          "version": 0
        },
        {
          "id": "65",
          "dictId": "9",
          "dataName": "镇",
          "dataCode": "镇",
          "seq": 16,
          "spId": null,
          "version": 0
        },
        {
          "id": "66",
          "dictId": "9",
          "dataName": "州",
          "dataCode": "州",
          "seq": 17,
          "spId": null,
          "version": 0
        },
        {
          "id": "67",
          "dictId": "9",
          "dataName": "院",
          "dataCode": "院",
          "seq": 18,
          "spId": null,
          "version": 0
        },
        {
          "id": "68",
          "dictId": "9",
          "dataName": "崖",
          "dataCode": "崖",
          "seq": 19,
          "spId": null,
          "version": 0
        },
        {
          "id": "69",
          "dictId": "9",
          "dataName": "谷",
          "dataCode": "谷",
          "seq": 20,
          "spId": null,
          "version": 0
        },
        {
          "id": "70",
          "dictId": "9",
          "dataName": "街",
          "dataCode": "街",
          "seq": 21,
          "spId": null,
          "version": 0
        },
        {
          "id": "71",
          "dictId": "9",
          "dataName": "寺",
          "dataCode": "寺",
          "seq": 22,
          "spId": null,
          "version": 0
        },
        {
          "id": "72",
          "dictId": "9",
          "dataName": "轩",
          "dataCode": "轩",
          "seq": 23,
          "spId": null,
          "version": 0
        },
        {
          "id": "73",
          "dictId": "9",
          "dataName": "园",
          "dataCode": "园",
          "seq": 24,
          "spId": null,
          "version": 0
        },
        {
          "id": "74",
          "dictId": "9",
          "dataName": "斋",
          "dataCode": "斋",
          "seq": 25,
          "spId": null,
          "version": 0
        },
        {
          "id": "75",
          "dictId": "9",
          "dataName": "峡",
          "dataCode": "峡",
          "seq": 26,
          "spId": null,
          "version": 0
        },
        {
          "id": "76",
          "dictId": "9",
          "dataName": "观",
          "dataCode": "观",
          "seq": 27,
          "spId": null,
          "version": 0
        },
        {
          "id": "77",
          "dictId": "9",
          "dataName": "寨",
          "dataCode": "寨",
          "seq": 28,
          "spId": null,
          "version": 0
        },
        {
          "id": "78",
          "dictId": "9",
          "dataName": "窟",
          "dataCode": "窟",
          "seq": 29,
          "spId": null,
          "version": 0
        },
        {
          "id": "79",
          "dictId": "9",
          "dataName": "堡",
          "dataCode": "堡",
          "seq": 30,
          "spId": null,
          "version": 0
        },
        {
          "id": "80",
          "dictId": "9",
          "dataName": "涧",
          "dataCode": "涧",
          "seq": 31,
          "spId": null,
          "version": 0
        },
        {
          "id": "81",
          "dictId": "9",
          "dataName": "台",
          "dataCode": "台",
          "seq": 32,
          "spId": null,
          "version": 0
        }
      ]
    }
  ],
  "configList": [],
  "funcComponentList": [
    {
      "id": "49",
      "funcId": "20",
      "name": "新增",
      "code": "add",
      "icon": null,
      "displayType": "primary",
      "comments": null
    },
    {
      "id": "50",
      "funcId": "20",
      "name": "编辑",
      "code": "update",
      "icon": null,
      "displayType": null,
      "comments": null
    },
    {
      "id": "51",
      "funcId": "20",
      "name": "删除",
      "code": "delete",
      "icon": null,
      "displayType": null,
      "comments": null
    }
  ],
  "metaModelList": [
    {
      "id": "20",
      "parentModelId": null,
      "relationship": null,
      "modelName": "地名",
      "modelCode": "diMing",
      "funcModelCode": "diMing",
      "searchFlag": "Y",
      "multChooseFlag": "Y",
      "title": null,
      "masterFlag": "Y",
      "treeTableFlag": "N",
      "childColumnCode": null,
      "parentColumnCode": null,
      "position": "1",
      "state": null,
      "stateTime": null,
      "columnList": [
        {
          "id": "150",
          "modelId": "20",
          "columnName": "id",
          "columnCode": "id",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 1,
          "requiredFlag": "Y",
          "searchFlag": "N",
          "profileDisplayFlag": "N",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "Y",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "151",
          "modelId": "20",
          "columnName": "地名代码",
          "columnCode": "diMingCode",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 3,
          "requiredFlag": "Y",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "152",
          "modelId": "20",
          "columnName": "地名名称",
          "columnCode": "diMingName",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 5,
          "requiredFlag": "Y",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "153",
          "modelId": "20",
          "columnName": "地名分类",
          "columnCode": "diMingFenLei",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "S",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": "dict|diMingFenLei",
          "seq": 7,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "154",
          "modelId": "20",
          "columnName": "地名描述",
          "columnCode": "diMingMiaoShu",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "T",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 9,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": "renderMiaoShu",
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "155",
          "modelId": "20",
          "columnName": "小说",
          "columnCode": "xiaoShuoId",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "S",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": "service|/xiuXing/common/xiu-xing/xiaoShuo",
          "seq": 11,
          "requiredFlag": "Y",
          "searchFlag": "Y",
          "profileDisplayFlag": "N",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "156",
          "modelId": "20",
          "columnName": "小说",
          "columnCode": "xiaoShuoName",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 13,
          "requiredFlag": "Y",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "157",
          "modelId": "20",
          "columnName": "更新时间",
          "columnCode": "updateTime",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 15,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": "160px",
          "titleFlag": "N"
        }
      ],
      "actionList": [
        {
          "id": "88",
          "modelId": "20",
          "type": "N",
          "code": "query",
          "name": null,
          "servId": "20",
          "servAction": "query",
          "defaultFlag": "Y",
          "disableRule": null,
          "propFlag": "N",
          "propMsg": null,
          "delErrorMsg": null,
          "servCode": null,
          "category": null,
          "seq": null,
          "displayType": null,
          "icon": null
        },
        {
          "id": "89",
          "modelId": "20",
          "type": "N",
          "code": "get",
          "name": null,
          "servId": "20",
          "servAction": "get",
          "defaultFlag": "Y",
          "disableRule": null,
          "propFlag": "N",
          "propMsg": null,
          "delErrorMsg": null,
          "servCode": null,
          "category": null,
          "seq": null,
          "displayType": null,
          "icon": null
        },
        {
          "id": "90",
          "modelId": "20",
          "type": "T",
          "code": "add",
          "name": "新增",
          "servId": "20",
          "servAction": "add",
          "defaultFlag": "Y",
          "disableRule": null,
          "propFlag": "N",
          "propMsg": null,
          "delErrorMsg": null,
          "servCode": null,
          "category": null,
          "seq": null,
          "displayType": "primary",
          "icon": null
        },
        {
          "id": "91",
          "modelId": "20",
          "type": "L",
          "code": "update",
          "name": "编辑",
          "servId": "20",
          "servAction": "update",
          "defaultFlag": "Y",
          "disableRule": null,
          "propFlag": "N",
          "propMsg": null,
          "delErrorMsg": null,
          "servCode": null,
          "category": null,
          "seq": null,
          "displayType": null,
          "icon": null
        },
        {
          "id": "92",
          "modelId": "20",
          "type": "L",
          "code": "delete",
          "name": "删除",
          "servId": "20",
          "servAction": "delete",
          "defaultFlag": "Y",
          "disableRule": null,
          "propFlag": "Y",
          "propMsg": null,
          "delErrorMsg": null,
          "servCode": null,
          "category": null,
          "seq": null,
          "displayType": null,
          "icon": null
        }
      ]
    }
  ]
};

export function diMingMetaModel() {
  return diMing;
}
