const fenLei = {
  "id": "28",
  "funcCode": "fenLei",
  "funcName": "分类",
  "state": "A",
  "stateTime": "2020-07-05 03:10:46",
  "seq": 28,
  "dictList": [
    {
      "id": "22",
      "funcId": "28",
      "dictName": "分类类型",
      "dictCode": "type",
      "seq": 1,
      "version": 0,
      "dictDataList": [
        {
          "id": "235",
          "dictId": "22",
          "dataName": "状态",
          "dataCode": "state",
          "seq": 1,
          "version": 0
        },
        {
          "id": "236",
          "dictId": "22",
          "dataName": "分类",
          "dataCode": "fenLei",
          "seq": 2,
          "version": 0
        }
      ]
    },
    {
      "id": "23",
      "funcId": "28",
      "dictName": "分类",
      "dictCode": "fenLei",
      "seq": 2,
      "version": 0,
      "dictDataList": [
        {
          "id": "237",
          "dictId": "23",
          "dataName": "灵物状态",
          "dataCode": "lingWuState",
          "seq": 1,
          "version": 0
        },
        {
          "id": "238",
          "dictId": "23",
          "dataName": "所属状态",
          "dataCode": "suoShuState",
          "seq": 2,
          "version": 0
        },
        {
          "id": "239",
          "dictId": "23",
          "dataName": "灵物分类",
          "dataCode": "lingWuFenLei",
          "seq": 3,
          "version": 0
        },
        {
          "id": "240",
          "dictId": "23",
          "dataName": "所属分类",
          "dataCode": "suoShuFenLei",
          "seq": 4,
          "version": 0
        },
        {
          "id": "ee8bac39c74b3a92477ef00782cff9fc",
          "dictId": "23",
          "dataName": "境界分类",
          "dataCode": "jingJieFenLei",
          "seq": 5,
          "version": 0
        }
      ]
    }
  ],
  "configList": [],
  "funcComponentList": [
    {
      "id": "67",
      "funcId": "28",
      "name": "新增",
      "code": "add",
      "displayType": "primary"
    },
    {
      "id": "68",
      "funcId": "28",
      "name": "编辑",
      "code": "update"
    },
    {
      "id": "69",
      "funcId": "28",
      "name": "删除",
      "code": "delete"
    }
  ],
  "metaModelList": [
    {
      "id": "28",
      "modelName": "分类",
      "modelCode": "fenLei",
      "funcModelCode": "fenLei",
      "searchFlag": "Y",
      "multChooseFlag": "Y",
      "masterFlag": "Y",
      "treeTableFlag": "N",
      "position": "1",
      "columnList": [
        {
          "id": "264",
          "modelId": "28",
          "columnName": "id",
          "columnCode": "id",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 1,
          "requiredFlag": "Y",
          "searchFlag": "N",
          "profileDisplayFlag": "N",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "Y",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "267",
          "modelId": "28",
          "columnName": "分类名称",
          "columnCode": "fenLeiName",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 3,
          "requiredFlag": "Y",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "266",
          "modelId": "28",
          "columnName": "分类编码",
          "columnCode": "fenLeiCode",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 5,
          "requiredFlag": "Y",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "265",
          "modelId": "28",
          "columnName": "分类类型",
          "columnCode": "type",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "S",
          "valueList": "dict|type",
          "seq": 7,
          "requiredFlag": "Y",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "269",
          "modelId": "28",
          "columnName": "分类",
          "columnCode": "fenLei",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "S",
          "valueList": "dict|fenLei",
          "seq": 8,
          "requiredFlag": "Y",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "268",
          "modelId": "28",
          "columnName": "分类描述",
          "columnCode": "fenLeiMiaoShu",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "T",
          "seq": 9,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": "renderMiaoShu",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A",
          "extStr01": "Y"
        },
        {
          "id": "ec4bde0c6510f69dc64604a1faedcc8f",
          "modelId": "28",
          "columnName": "小说",
          "columnCode": "xiaoShuoId",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "S",
          "valueList": "service|/xiuXing/common/xiu-xing/xiaoShuo",
          "seq": 11,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "N",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "cb46401ac366fff7e8335b83c3aea390",
          "modelId": "28",
          "columnName": "小说",
          "columnCode": "xiaoShuoName",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 13,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        }
      ],
      "actionList": [
        {
          "id": "122",
          "modelId": "28",
          "type": "N",
          "code": "query",
          "servId": "28",
          "servAction": "query",
          "defaultFlag": "Y",
          "propFlag": "N",
          "seq": 1
        },
        {
          "id": "123",
          "modelId": "28",
          "type": "N",
          "code": "get",
          "servId": "28",
          "servAction": "get",
          "defaultFlag": "Y",
          "propFlag": "N",
          "seq": 2
        },
        {
          "id": "124",
          "modelId": "28",
          "type": "T",
          "code": "add",
          "name": "新增",
          "servId": "28",
          "servAction": "add",
          "defaultFlag": "Y",
          "propFlag": "N",
          "seq": 3,
          "displayType": "primary"
        },
        {
          "id": "125",
          "modelId": "28",
          "type": "L",
          "code": "update",
          "name": "编辑",
          "servId": "28",
          "servAction": "update",
          "defaultFlag": "Y",
          "propFlag": "N",
          "seq": 5
        },
        {
          "id": "126",
          "modelId": "28",
          "type": "L",
          "code": "delete",
          "name": "删除",
          "servId": "28",
          "servAction": "delete",
          "defaultFlag": "Y",
          "propFlag": "Y",
          "seq": 6
        }
      ]
    }
  ]
};

export function fenLeiMetaModel() {
  return fenLei;
}
