const renWu = {
  "id": "1",
  "icon": null,
  "funcCode": "renWu",
  "funcName": "人物",
  "state": "A",
  "comments": null,
  "stateTime": "2020-05-30 02:26:28",
  "seq": 1,
  "indexUrl": null,
  "dictList": [
    {
      "id": "1",
      "funcId": "1",
      "dictName": "人物分类",
      "dictCode": "renWuFenLei",
      "comments": null,
      "category": null,
      "modifyFlag": null,
      "visiableFlag": null,
      "seq": 1,
      "spId": null,
      "version": 0,
      "dictDataList": [
        {
          "id": "1",
          "dictId": "1",
          "dataName": "人",
          "dataCode": "人",
          "seq": 1,
          "spId": null,
          "version": 0
        },
        {
          "id": "10",
          "dictId": "1",
          "dataName": "妖",
          "dataCode": "妖",
          "seq": 9,
          "spId": null,
          "version": 0
        },
        {
          "id": "11",
          "dictId": "1",
          "dataName": "阵法",
          "dataCode": "阵法",
          "seq": 10,
          "spId": null,
          "version": 0
        },
        {
          "id": "12",
          "dictId": "1",
          "dataName": "其他灵物",
          "dataCode": "其他灵物",
          "seq": 11,
          "spId": null,
          "version": 0
        },
        {
          "id": "13",
          "dictId": "1",
          "dataName": "兽",
          "dataCode": "兽",
          "seq": 12,
          "spId": null,
          "version": 0
        },
        {
          "id": "14",
          "dictId": "1",
          "dataName": "魔",
          "dataCode": "魔",
          "seq": 13,
          "spId": null,
          "version": 0
        },
        {
          "id": "15",
          "dictId": "1",
          "dataName": "鬼",
          "dataCode": "鬼",
          "seq": 14,
          "spId": null,
          "version": 0
        },
        {
          "id": "16",
          "dictId": "1",
          "dataName": "怪",
          "dataCode": "怪",
          "seq": 15,
          "spId": null,
          "version": 0
        },
        {
          "id": "17",
          "dictId": "1",
          "dataName": "神",
          "dataCode": "神",
          "seq": 16,
          "spId": null,
          "version": 0
        },
        {
          "id": "18",
          "dictId": "1",
          "dataName": "仙",
          "dataCode": "仙",
          "seq": 17,
          "spId": null,
          "version": 0
        },
        {
          "id": "19",
          "dictId": "1",
          "dataName": "佛",
          "dataCode": "佛",
          "seq": 18,
          "spId": null,
          "version": 0
        },
        {
          "id": "20",
          "dictId": "1",
          "dataName": "儒",
          "dataCode": "儒",
          "seq": 19,
          "spId": null,
          "version": 0
        },
        {
          "id": "21",
          "dictId": "1",
          "dataName": "僵尸",
          "dataCode": "僵尸",
          "seq": 20,
          "spId": null,
          "version": 0
        },
        {
          "id": "3",
          "dictId": "1",
          "dataName": "符箓",
          "dataCode": "符箓",
          "seq": 2,
          "spId": null,
          "version": 0
        },
        {
          "id": "4",
          "dictId": "1",
          "dataName": "法术",
          "dataCode": "法术",
          "seq": 3,
          "spId": null,
          "version": 0
        },
        {
          "id": "5",
          "dictId": "1",
          "dataName": "神通",
          "dataCode": "神通",
          "seq": 4,
          "spId": null,
          "version": 0
        },
        {
          "id": "6",
          "dictId": "1",
          "dataName": "傀儡",
          "dataCode": "傀儡",
          "seq": 5,
          "spId": null,
          "version": 0
        },
        {
          "id": "7",
          "dictId": "1",
          "dataName": "灵材",
          "dataCode": "灵材",
          "seq": 6,
          "spId": null,
          "version": 0
        },
        {
          "id": "8",
          "dictId": "1",
          "dataName": "灵丹",
          "dataCode": "灵丹",
          "seq": 7,
          "spId": null,
          "version": 0
        },
        {
          "id": "9",
          "dictId": "1",
          "dataName": "灵器",
          "dataCode": "灵器",
          "seq": 8,
          "spId": null,
          "version": 0
        }
      ]
    },
    {
      "id": "2",
      "funcId": "1",
      "dictName": "人物状态",
      "dictCode": "renWuState",
      "comments": null,
      "category": null,
      "modifyFlag": null,
      "visiableFlag": null,
      "seq": 2,
      "spId": null,
      "version": 0,
      "dictDataList": [
        {
          "id": "2",
          "dictId": "2",
          "dataName": "已死亡",
          "dataCode": "已死亡",
          "seq": 1,
          "spId": null,
          "version": 0
        }
      ]
    }
  ],
  "configList": [],
  "funcComponentList": [
    {
      "id": "1",
      "funcId": "1",
      "name": "新增",
      "code": "add",
      "icon": null,
      "displayType": "primary",
      "comments": null
    },
    {
      "id": "2",
      "funcId": "1",
      "name": "编辑",
      "code": "update",
      "icon": null,
      "displayType": null,
      "comments": null
    },
    {
      "id": "3",
      "funcId": "1",
      "name": "删除",
      "code": "delete",
      "icon": null,
      "displayType": null,
      "comments": null
    }
  ],
  "metaModelList": [
    {
      "id": "1",
      "parentModelId": "",
      "relationship": null,
      "modelName": "人物",
      "modelCode": "renWu",
      "funcModelCode": "renWu",
      "searchFlag": "Y",
      "multChooseFlag": "Y",
      "title": null,
      "masterFlag": "Y",
      "treeTableFlag": "N",
      "childColumnCode": null,
      "parentColumnCode": null,
      "position": "1",
      "state": null,
      "stateTime": null,
      "columnList": [
        {
          "id": "1",
          "modelId": "1",
          "columnName": "id",
          "columnCode": "id",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 1,
          "requiredFlag": "Y",
          "searchFlag": "N",
          "profileDisplayFlag": "N",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "Y",
          "feignFlag": "N",
          "columnWidth": null,
          "titleFlag": "N"
        },
        {
          "id": "2",
          "modelId": "1",
          "columnName": "人物代码",
          "columnCode": "renWuCode",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 2,
          "requiredFlag": "Y",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": "90px",
          "titleFlag": "N"
        },
        {
          "id": "3",
          "modelId": "1",
          "columnName": "人物名称",
          "columnCode": "renWuName",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 3,
          "requiredFlag": "Y",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": "110px",
          "titleFlag": "N"
        },
        {
          "id": "4",
          "modelId": "1",
          "columnName": "曾用名",
          "columnCode": "cengYongMing",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 4,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": "110px",
          "titleFlag": "N"
        },
        {
          "id": "5",
          "modelId": "1",
          "columnName": "人物分类",
          "columnCode": "renWuFenLei",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "MS",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": "dict|renWuFenLei",
          "seq": 5,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": "110px",
          "titleFlag": "N"
        },
        {
          "id": "6",
          "modelId": "1",
          "columnName": "人物状态",
          "columnCode": "renWuState",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "S",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": "dict|renWuState",
          "seq": 6,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": "90px",
          "titleFlag": "N"
        },
        {
          "id": "7",
          "modelId": "1",
          "columnName": "人物属性",
          "columnCode": "renWuShuXing",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "T",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 7,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": "renderRenWuShuXing",
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": "250px",
          "titleFlag": "N"
        },
        {
          "id": "8",
          "modelId": "1",
          "columnName": "人物描述",
          "columnCode": "renWuMiaoShu",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "T",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 8,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": "renderRenWuMiaoShu",
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": "250px",
          "titleFlag": "N"
        },
        {
          "id": "9",
          "modelId": "1",
          "columnName": "小说",
          "columnCode": "xiaoShuoName",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 9,
          "requiredFlag": "Y",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": "110px",
          "titleFlag": "N"
        },
        {
          "id": "10",
          "modelId": "1",
          "columnName": "更新时间",
          "columnCode": "updateTime",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "I",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": null,
          "seq": 10,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": "160px",
          "titleFlag": "N"
        },
        {
          "id": "11",
          "modelId": "1",
          "columnName": "小说",
          "columnCode": "xiaoShuoId",
          "valueType": "S",
          "defaultValue": null,
          "modifyFlag": "N",
          "displayType": "S",
          "comments": null,
          "errorText": null,
          "validateRule": null,
          "valueList": "service|/xiuXing/common/xiu-xing/xiaoShuo",
          "seq": 11,
          "requiredFlag": "Y",
          "searchFlag": "Y",
          "profileDisplayFlag": "N",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": null,
          "renderProfile": null,
          "renderEdit": null,
          "primaryFlag": "N",
          "feignFlag": "N",
          "columnWidth": "110px",
          "titleFlag": "N"
        }
      ],
      "actionList": [
        {
          "id": "1",
          "modelId": "1",
          "type": "N",
          "code": "query",
          "name": null,
          "servId": "1",
          "servAction": "query",
          "defaultFlag": "Y",
          "disableRule": null,
          "propFlag": "N",
          "propMsg": null,
          "delErrorMsg": null,
          "servCode": null,
          "category": null,
          "seq": null,
          "displayType": null,
          "icon": null
        },
        {
          "id": "2",
          "modelId": "1",
          "type": "N",
          "code": "get",
          "name": null,
          "servId": "1",
          "servAction": "get",
          "defaultFlag": "Y",
          "disableRule": null,
          "propFlag": "N",
          "propMsg": null,
          "delErrorMsg": null,
          "servCode": null,
          "category": null,
          "seq": null,
          "displayType": null,
          "icon": null
        },
        {
          "id": "3",
          "modelId": "1",
          "type": "T",
          "code": "add",
          "name": "新增",
          "servId": "1",
          "servAction": "add",
          "defaultFlag": "Y",
          "disableRule": null,
          "propFlag": "N",
          "propMsg": null,
          "delErrorMsg": null,
          "servCode": null,
          "category": null,
          "seq": null,
          "displayType": "primary",
          "icon": null
        },
        {
          "id": "5",
          "modelId": "1",
          "type": "L",
          "code": "update",
          "name": "编辑",
          "servId": "1",
          "servAction": "update",
          "defaultFlag": "Y",
          "disableRule": null,
          "propFlag": "N",
          "propMsg": null,
          "delErrorMsg": null,
          "servCode": null,
          "category": null,
          "seq": null,
          "displayType": null,
          "icon": null
        },
        {
          "id": "6",
          "modelId": "1",
          "type": "L",
          "code": "delete",
          "name": "删除",
          "servId": "1",
          "servAction": "delete",
          "defaultFlag": "Y",
          "disableRule": null,
          "propFlag": "Y",
          "propMsg": null,
          "delErrorMsg": null,
          "servCode": null,
          "category": null,
          "seq": null,
          "displayType": null,
          "icon": null
        }
      ]
    }
  ]
};

export function renWuMetaModel() {
  return renWu;
}
