const shengWuFenLei = {
  "id": "39",
  "funcCode": "shengWuFenLei",
  "funcName": "生物分类",
  "state": "A",
  "stateTime": "2020-11-14 20:09:02",
  "seq": 39,
  "dictList": [],
  "configList": [],
  "funcComponentList": [
    {
      "id": "12ffd372936d476aa1c21d33fccdbe4c",
      "funcId": "39",
      "name": "编辑",
      "code": "update"
    },
    {
      "id": "27d66ac724c9488bbe25a78ca7a34f1c",
      "funcId": "39",
      "name": "新增",
      "code": "add",
      "displayType": "primary"
    },
    {
      "id": "9557f3ab0d774bc5af533ccac06ceb41",
      "funcId": "39",
      "name": "删除",
      "code": "delete"
    }
  ],
  "metaModelList": [
    {
      "id": "39",
      "modelName": "生物分类",
      "modelCode": "shengWuFenLei",
      "funcModelCode": "shengWuFenLei",
      "searchFlag": "Y",
      "multChooseFlag": "Y",
      "masterFlag": "Y",
      "treeTableFlag": "N",
      "position": "1",
      "columnList": [
        {
          "id": "56de0315be3d498c851ad5e4ea69a1a5",
          "modelId": "39",
          "columnName": "id",
          "columnCode": "id",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 1,
          "requiredFlag": "Y",
          "searchFlag": "N",
          "profileDisplayFlag": "N",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "Y",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "053e44ff89a849c5ae4901499733c6e4",
          "modelId": "39",
          "columnName": "编码",
          "columnCode": "code",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 3,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "dae83df989414dd89e6c5fa513879f86",
          "modelId": "39",
          "columnName": "域",
          "columnCode": "yu",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "CF",
          "valueList": "service|/xiuXing/shengWuFenLei/fenLei?leiBie=yu",
          "seq": 5,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "0594335b290e49139a840650c07a848e",
          "modelId": "39",
          "columnName": "界",
          "columnCode": "jie",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "CF",
          "valueList": "service|/xiuXing/shengWuFenLei/fenLei?leiBie=jie",
          "seq": 7,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "e1f04b1974764310be331b89cf012255",
          "modelId": "39",
          "columnName": "亚界",
          "columnCode": "yaJie",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "CF",
          "valueList": "service|/xiuXing/shengWuFenLei/fenLei?leiBie=yaJie",
          "seq": 9,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "377adb4496cc439aa50ef786836620b0",
          "modelId": "39",
          "columnName": "门",
          "columnCode": "men",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "CF",
          "valueList": "service|/xiuXing/shengWuFenLei/fenLei?leiBie=men",
          "seq": 11,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "813f67ee4bfe498e9ef3063c1744d238",
          "modelId": "39",
          "columnName": "亚门",
          "columnCode": "yaMen",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "CF",
          "valueList": "service|/xiuXing/shengWuFenLei/fenLei?leiBie=yaMen",
          "seq": 13,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "e2f15fe1c28b4775b7bcde01e7561b49",
          "modelId": "39",
          "columnName": "纲",
          "columnCode": "gang",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "CF",
          "valueList": "service|/xiuXing/shengWuFenLei/fenLei?leiBie=gang",
          "seq": 15,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "346825dc6c5345c08d29013dde9a32fd",
          "modelId": "39",
          "columnName": "亚纲",
          "columnCode": "yaGang",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "CF",
          "valueList": "service|/xiuXing/shengWuFenLei/fenLei?leiBie=yaGang",
          "seq": 17,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "3f913de7b2c244e882082d705853e8dc",
          "modelId": "39",
          "columnName": "总目",
          "columnCode": "zongMu",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "CF",
          "valueList": "service|/xiuXing/shengWuFenLei/fenLei?leiBie=zongMu",
          "seq": 19,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "32634cdbed1748e3a0032358f32b2659",
          "modelId": "39",
          "columnName": "目",
          "columnCode": "mu",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "CF",
          "valueList": "service|/xiuXing/shengWuFenLei/fenLei?leiBie=mu",
          "seq": 21,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "85a5f579c9ee41479449bb673c2b65cd",
          "modelId": "39",
          "columnName": "科",
          "columnCode": "ke",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "CF",
          "valueList": "service|/xiuXing/shengWuFenLei/fenLei?leiBie=ke",
          "seq": 23,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "1345cb51cc284a07b6e065f49593d401",
          "modelId": "39",
          "columnName": "属",
          "columnCode": "shu",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "CF",
          "valueList": "service|/xiuXing/shengWuFenLei/fenLei?leiBie=shu",
          "seq": 25,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "9dc7b39a877447ad83f969b03e95f96e",
          "modelId": "39",
          "columnName": "种",
          "columnCode": "zhong",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "CF",
          "valueList": "service|/xiuXing/shengWuFenLei/fenLei?leiBie=zhong",
          "seq": 27,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "0507210b2b874836a8720b81d9db973d",
          "modelId": "39",
          "columnName": "描述",
          "columnCode": "comments",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "T",
          "seq": 29,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": "renderMiaoShu",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A",
          "extStr01": "Y"
        }
      ],
      "actionList": [
        {
          "id": "8b73c0c7a38242c8a969785bf9a8bf10",
          "modelId": "39",
          "type": "N",
          "code": "query",
          "servId": "39",
          "servAction": "query",
          "defaultFlag": "Y",
          "propFlag": "N",
          "seq": 1
        },
        {
          "id": "71c45ab38c0847219df577ef98ebcd09",
          "modelId": "39",
          "type": "N",
          "code": "get",
          "servId": "39",
          "servAction": "get",
          "defaultFlag": "Y",
          "propFlag": "N",
          "seq": 2
        },
        {
          "id": "c86f9d60db244567ab5b59c75a88295a",
          "modelId": "39",
          "type": "T",
          "code": "add",
          "name": "新增",
          "servId": "39",
          "servAction": "add",
          "defaultFlag": "Y",
          "propFlag": "N",
          "seq": 3,
          "displayType": "primary"
        },
        {
          "id": "183494791e174be3abb12bddf00c55c6",
          "modelId": "39",
          "type": "L",
          "code": "update",
          "name": "编辑",
          "servId": "39",
          "servAction": "update",
          "defaultFlag": "Y",
          "propFlag": "N",
          "seq": 5
        },
        {
          "id": "313854bd71ac4b85ad532e4c0df98afa",
          "modelId": "39",
          "type": "L",
          "code": "delete",
          "name": "删除",
          "servId": "39",
          "servAction": "delete",
          "defaultFlag": "Y",
          "propFlag": "Y",
          "seq": 6
        }
      ]
    }
  ]
}

export function shengWuFenLeiMetaModel() {
  return shengWuFenLei;
}
