const suoShu = {
  "id": "22",
  "funcCode": "suoShu",
  "funcName": "所属",
  "state": "A",
  "stateTime": "2020-06-25 02:02:09",
  "seq": 22,
  "dictList": [
    {
      "id": "16",
      "funcId": "22",
      "dictName": "所属分类",
      "dictCode": "suoShuFenLei",
      "seq": 1,
      "version": 0,
      "dictDataList": [
        {
          "id": "060f14d421b08b3b32ffa297231b8229",
          "dictId": "16",
          "dataName": "修行者",
          "dataCode": "xiuXingZhe",
          "seq": 6,
          "version": 0
        },
        {
          "id": "147",
          "dictId": "16",
          "dataName": "宗门",
          "dataCode": "zongMen",
          "seq": 1,
          "version": 0
        },
        {
          "id": "148",
          "dictId": "16",
          "dataName": "家族",
          "dataCode": "jiaZu",
          "seq": 2,
          "version": 0
        },
        {
          "id": "149",
          "dictId": "16",
          "dataName": "组织",
          "dataCode": "zuZhi",
          "seq": 3,
          "version": 0
        },
        {
          "id": "150",
          "dictId": "16",
          "dataName": "机构",
          "dataCode": "jiGou",
          "seq": 4,
          "version": 0
        },
        {
          "id": "151",
          "dictId": "16",
          "dataName": "地名",
          "dataCode": "diMing",
          "seq": 5,
          "version": 0
        }
      ]
    }
  ],
  "configList": [],
  "funcComponentList": [
    {
      "id": "55",
      "funcId": "22",
      "name": "新增",
      "code": "add",
      "displayType": "primary"
    },
    {
      "id": "56",
      "funcId": "22",
      "name": "编辑",
      "code": "update"
    },
    {
      "id": "57",
      "funcId": "22",
      "name": "删除",
      "code": "delete"
    },
    {
      "id": "a985187eb15c2041d3cb4723db885998",
      "funcId": "22",
      "name": "仓库",
      "code": "ck"
    },
    {
      "id": "ff90ad64eb0bc10be537937dd1cda0e3",
      "funcId": "22",
      "name": "操作记录",
      "code": "opt"
    }
  ],
  "metaModelList": [
    {
      "id": "22",
      "modelName": "所属",
      "modelCode": "suoShu",
      "funcModelCode": "suoShu",
      "searchFlag": "Y",
      "multChooseFlag": "Y",
      "masterFlag": "Y",
      "treeTableFlag": "N",
      "position": "1",
      "columnList": [
        {
          "id": "182",
          "modelId": "22",
          "columnName": "id",
          "columnCode": "id",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 1,
          "requiredFlag": "Y",
          "searchFlag": "N",
          "profileDisplayFlag": "N",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "Y",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "201",
          "modelId": "22",
          "columnName": "所属编码",
          "columnCode": "suoShuCode",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 2,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "184",
          "modelId": "22",
          "columnName": "所属名称",
          "columnCode": "suoShuName",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 3,
          "requiredFlag": "Y",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "183",
          "modelId": "22",
          "columnName": "所属分类",
          "columnCode": "suoShuFenLei",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "S",
          "valueList": "service|xiuXing/common/xiu-xing/fenLei?type=fenLei&fenLei=suoShuFenLei",
          "seq": 5,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "N",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "bec3b7e10c4c92c9d0a01740ad25ac7c",
          "modelId": "22",
          "columnName": "所属分类",
          "columnCode": "suoShuFenLeiName",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 5,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "185",
          "modelId": "22",
          "columnName": "所属描述",
          "columnCode": "suoShuMiaoShu",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "T",
          "seq": 7,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": "renderMiaoShu",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A",
          "extStr01": "Y"
        },
        {
          "id": "262",
          "modelId": "22",
          "columnName": "地址",
          "columnCode": "addrId",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "CF",
          "valueList": "service|/xiuXing/common/xiu-xing/address",
          "seq": 8,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "N",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "263",
          "modelId": "22",
          "columnName": "地址",
          "columnCode": "addrFullName",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 9,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": "renderMiaoShu",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A",
          "extStr01": "Y"
        },
        {
          "id": "186",
          "modelId": "22",
          "columnName": "小说",
          "columnCode": "xiaoShuoId",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "S",
          "valueList": "service|/xiuXing/common/xiu-xing/xiaoShuo",
          "seq": 10,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "N",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "187",
          "modelId": "22",
          "columnName": "小说",
          "columnCode": "xiaoShuoName",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 11,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        }
      ],
      "actionList": [
        {
          "id": "98",
          "modelId": "22",
          "type": "N",
          "code": "query",
          "servId": "22",
          "servAction": "query",
          "defaultFlag": "Y",
          "propFlag": "N",
          "seq": 1
        },
        {
          "id": "99",
          "modelId": "22",
          "type": "N",
          "code": "get",
          "servId": "22",
          "servAction": "get",
          "defaultFlag": "Y",
          "propFlag": "N",
          "seq": 2
        },
        {
          "id": "105",
          "modelId": "22",
          "type": "T",
          "code": "add",
          "name": "新增",
          "servId": "22",
          "servAction": "add",
          "defaultFlag": "Y",
          "propFlag": "N",
          "seq": 3,
          "displayType": "primary"
        },
        {
          "id": "15ac5269ed5395cefe65e46840bd8d47",
          "modelId": "22",
          "type": "L",
          "code": "ck",
          "name": "仓库",
          "servId": "22",
          "servAction": "ck",
          "defaultFlag": "N",
          "propFlag": "N",
          "seq": 3
        },
        {
          "id": "8e76b04705e7abba77d0c6ea4e7c4028",
          "modelId": "22",
          "type": "L",
          "code": "opt",
          "name": "操作记录",
          "servId": "22",
          "servAction": "opt",
          "defaultFlag": "N",
          "propFlag": "N",
          "seq": 4
        },
        {
          "id": "106",
          "modelId": "22",
          "type": "L",
          "code": "update",
          "name": "编辑",
          "servId": "22",
          "servAction": "update",
          "defaultFlag": "Y",
          "propFlag": "N",
          "seq": 5
        },
        {
          "id": "107",
          "modelId": "22",
          "type": "L",
          "code": "delete",
          "name": "删除",
          "servId": "22",
          "servAction": "delete",
          "defaultFlag": "Y",
          "disableRule": "(data, column) => data.suoShuHisCount > 0",
          "propFlag": "Y",
          "seq": 7
        }
      ]
    }
  ]
};

export function suoShuMetaModel() {
  return suoShu;
}
