const xiaoShuo = {
  id: '3',
  funcCode: 'xiaoShuo',
  funcName: '小说',
  state: 'A',
  stateTime: '2020-06-11 15:31:32',
  seq: 3,
  dictList: [],
  configList: [],
  funcComponentList: [
    {
      id: '115',
      funcId: '3',
      name: '置顶',
      code: 'modify',
    },
  ],
  metaModelList: [
    {
      id: '3',
      modelName: '小说',
      modelCode: 'xiaoShuo',
      funcModelCode: 'xiaoShuo',
      searchFlag: 'Y',
      multChooseFlag: 'Y',
      masterFlag: 'Y',
      treeTableFlag: 'N',
      position: '1',
      columnList: [
        {
          id: '21',
          modelId: '3',
          columnName: 'id',
          columnCode: 'id',
          valueType: 'S',
          modifyFlag: 'N',
          displayType: 'I',
          seq: 1,
          requiredFlag: 'Y',
          searchFlag: 'N',
          profileDisplayFlag: 'N',
          addTable: 'N',
          editDisplayFlag: 'N',
          editable: 'N',
          listDisplayFlag: 'N',
          exportDisplayFlag: 'N',
          sortable: 'N',
          primaryFlag: 'Y',
          feignFlag: 'N',
          titleFlag: 'N',
          state: 'A',
        },
        {
          id: '22',
          modelId: '3',
          columnName: '小说名称',
          columnCode: 'name',
          valueType: 'S',
          modifyFlag: 'N',
          displayType: 'I',
          seq: 3,
          requiredFlag: 'Y',
          searchFlag: 'Y',
          profileDisplayFlag: 'Y',
          addTable: 'N',
          editDisplayFlag: 'N',
          editable: 'N',
          listDisplayFlag: 'Y',
          exportDisplayFlag: 'N',
          sortable: 'N',
          renderList: 'renderXiaoShuoName',
          primaryFlag: 'N',
          feignFlag: 'N',
          titleFlag: 'N',
          state: 'A',
        },
        {
          id: '23',
          modelId: '3',
          columnName: '小说作者',
          columnCode: 'zuoZhe',
          valueType: 'S',
          modifyFlag: 'N',
          displayType: 'I',
          seq: 5,
          requiredFlag: 'Y',
          searchFlag: 'Y',
          profileDisplayFlag: 'Y',
          addTable: 'N',
          editDisplayFlag: 'N',
          editable: 'N',
          listDisplayFlag: 'Y',
          exportDisplayFlag: 'N',
          sortable: 'N',
          primaryFlag: 'N',
          feignFlag: 'N',
          titleFlag: 'N',
          state: 'A',
        },
        {
          id: '24',
          modelId: '3',
          columnName: '小说描述',
          columnCode: 'xiaoShuoMiaoShu',
          valueType: 'S',
          modifyFlag: 'N',
          displayType: 'T',
          seq: 7,
          requiredFlag: 'N',
          searchFlag: 'Y',
          profileDisplayFlag: 'Y',
          addTable: 'N',
          editDisplayFlag: 'N',
          editable: 'N',
          listDisplayFlag: 'Y',
          exportDisplayFlag: 'N',
          sortable: 'N',
          primaryFlag: 'N',
          feignFlag: 'N',
          titleFlag: 'N',
          state: 'A',
        },
      ],
      actionList: [
        {
          id: '9',
          modelId: '3',
          type: 'N',
          code: 'query',
          servId: '3',
          servAction: 'query',
          defaultFlag: 'Y',
          propFlag: 'N',
          seq: 1,
        },
        {
          id: '196',
          modelId: '3',
          type: 'L',
          code: 'modify',
          name: '置顶',
          servId: '3',
          servAction: 'modify',
          defaultFlag: 'Y',
          disableRule: "(data, column)=> data.topping === 'Y'",
          propFlag: 'Y',
          seq: 1,
        },
        {
          id: '10',
          modelId: '3',
          type: 'N',
          code: 'get',
          servId: '3',
          servAction: 'get',
          defaultFlag: 'Y',
          propFlag: 'N',
          seq: 2,
        },
      ],
    },
  ],
};

export function xiaoShuoMetaModel() {
  return xiaoShuo;
}
