const zhangJie = {
  "id": "37",
  "funcCode": "zhangJie",
  "funcName": "章节",
  "state": "A",
  "stateTime": "2020-10-13 23:10:20",
  "seq": 37,
  "dictList": [],
  "configList": [],
  "funcComponentList": [
    {
      "id": "20c07177503d4c8cb4a6d6f8b8c9c1d6",
      "funcId": "37",
      "name": "删除",
      "code": "delete"
    },
    {
      "id": "aaca713bad384b119bd433c5955467be",
      "funcId": "37",
      "name": "新增",
      "code": "add",
      "displayType": "primary"
    },
    {
      "id": "f1c11ab49eb0473198c76ecc6870b7d2",
      "funcId": "37",
      "name": "编辑",
      "code": "update"
    }
  ],
  "metaModelList": [
    {
      "id": "37",
      "modelName": "章节",
      "modelCode": "zhangJie",
      "funcModelCode": "zhangJie",
      "searchFlag": "Y",
      "multChooseFlag": "Y",
      "masterFlag": "Y",
      "treeTableFlag": "N",
      "position": "1",
      "columnList": [
        {
          "id": "bdcf0a7d2deb470a8bbd8cd2407309ab",
          "modelId": "37",
          "columnName": "id",
          "columnCode": "id",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 1,
          "requiredFlag": "Y",
          "searchFlag": "N",
          "profileDisplayFlag": "N",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "Y",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "835ebd7aa20f43bda69905b3d9e373a8",
          "modelId": "37",
          "columnName": "章节编码",
          "columnCode": "zhangJieCode",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 3,
          "requiredFlag": "Y",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "Y",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "b1608be5036041c0b73ebeb77e4675b9",
          "modelId": "37",
          "columnName": "章节标题",
          "columnCode": "zhangJieTitle",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 5,
          "requiredFlag": "Y",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "a70c163ab1a841e2ad3a001cde1328f8",
          "modelId": "37",
          "columnName": "章节简介",
          "columnCode": "zhangJieJianJie",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "T",
          "seq": 7,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": "renderMiaoShu",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A",
          "extStr01": "Y"
        },
        {
          "id": "257781c1901245bd97c893387e5ef959",
          "modelId": "37",
          "columnName": "从信息",
          "columnCode": "congInfo",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "CF",
          "valueList": "service|xiuXing/common/xiu-xing/cong",
          "seq": 9,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "N",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "bb7cdb614cd1442f8a0e3d0223ef5686",
          "modelId": "37",
          "columnName": "从信息",
          "columnCode": "congInfoName",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 10,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": "renderCongInfoName",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A",
          "extStr01": "Y"
        },
        {
          "id": "8d13f6d5d653441794d0fa1739ba720b",
          "modelId": "37",
          "columnName": "属信息",
          "columnCode": "shuInfo",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "CF",
          "valueList": "service|xiuXing/common/xiu-xing/shu",
          "seq": 11,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "N",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "4a4240255252499bab2022f35313018f",
          "modelId": "37",
          "columnName": "属信息",
          "columnCode": "shuInfoName",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 12,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "renderList": "renderShuInfoName",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A",
          "extStr01": "Y"
        },
        {
          "id": "6b7b29b13454443daee7d6012c7d5ba8",
          "modelId": "37",
          "columnName": "小说",
          "columnCode": "xiaoShuoId",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "S",
          "valueList": "service|/xiuXing/common/xiu-xing/xiaoShuo",
          "seq": 13,
          "requiredFlag": "N",
          "searchFlag": "Y",
          "profileDisplayFlag": "N",
          "addTable": "Y",
          "editDisplayFlag": "N",
          "editable": "Y",
          "listDisplayFlag": "N",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        },
        {
          "id": "211ab772b5c74c18941e160f0dab08b6",
          "modelId": "37",
          "columnName": "小说",
          "columnCode": "xiaoShuoName",
          "valueType": "S",
          "modifyFlag": "N",
          "displayType": "I",
          "seq": 15,
          "requiredFlag": "N",
          "searchFlag": "N",
          "profileDisplayFlag": "Y",
          "addTable": "N",
          "editDisplayFlag": "N",
          "editable": "N",
          "listDisplayFlag": "Y",
          "exportDisplayFlag": "N",
          "sortable": "N",
          "primaryFlag": "N",
          "feignFlag": "N",
          "titleFlag": "N",
          "state": "A"
        }
      ],
      "actionList": [
        {
          "id": "e2cbc49cebfc4c41b08a023e72b47042",
          "modelId": "37",
          "type": "N",
          "code": "query",
          "servId": "37",
          "servAction": "query",
          "defaultFlag": "Y",
          "propFlag": "N",
          "seq": 1
        },
        {
          "id": "30aaa5ac467743c89ade7f1401424272",
          "modelId": "37",
          "type": "N",
          "code": "get",
          "servId": "37",
          "servAction": "get",
          "defaultFlag": "Y",
          "propFlag": "N",
          "seq": 2
        },
        {
          "id": "c3b5e4ce343647c8aac10062baac4da7",
          "modelId": "37",
          "type": "T",
          "code": "add",
          "name": "新增",
          "servId": "37",
          "servAction": "add",
          "defaultFlag": "Y",
          "propFlag": "N",
          "seq": 3,
          "displayType": "primary"
        },
        {
          "id": "f251392a028d45fcae59dc6d180e1ede",
          "modelId": "37",
          "type": "L",
          "code": "update",
          "name": "编辑",
          "servId": "37",
          "servAction": "update",
          "defaultFlag": "Y",
          "propFlag": "N",
          "seq": 5
        },
        {
          "id": "e8e0fffbe90c45dba6941549b3d5402f",
          "modelId": "37",
          "type": "L",
          "code": "delete",
          "name": "删除",
          "servId": "37",
          "servAction": "delete",
          "defaultFlag": "Y",
          "disableRule": "(data, column) => data.zhangJieCongShuInfoCount > 1",
          "propFlag": "Y",
          "seq": 6
        }
      ]
    }
  ]
};

export function zhangJieMetaModel() {
  return zhangJie;
}
